### ISSUE TITLE
The 3 algorithm buttons are hidden

### ISSUE THREAD

**Issue by rsmath** [NishanthPrajith18/Convex_Hull_Visualization#1]
## The buttons are hidden until hovered at. They were only found when a user inspected the webpage with Chrome dev tool and found the ```onclick()``` function being applied at an empty area which turns out to be the buttons.

<img width="1440" alt="Screen Shot 2020-10-10 at 5 59 38 PM" src="https://user-images.githubusercontent.com/24642071/95655073-75517b80-0b22-11eb-9760-631045535b23.png">
<img width="1440" alt="Screen Shot 2020-10-10 at 5 59 45 PM" src="https://user-images.githubusercontent.com/24642071/95655067-6ec30400-0b22-11eb-82c3-08e3567a6bad.png">
<img width="1440" alt="Screen Shot 2020-10-10 at 5 59 43 PM" src="https://user-images.githubusercontent.com/24642071/95655072-72ef2180-0b22-11eb-9d6b-d57a36f4f852.png">

**Comment by NishanthPrajith** [comment]
I am aware of that issue but it was done on purpose. If you look at the bottom u will notice a scroll to see the other points. And the thing is that there is like 200 points which I am using to take up the whole area to create a more neat visualization. So I was not exactly trying to use media queries to make it responsive. But point noted. Also the divide and conquer is not there I am trying to figure out a neat visualization for it.

**Comment by rsmath** [comment]
They just needed to be visible so people could interact with them, which they now are. :+1:
